### PHP-Version ############################################
    FROM php:7.0-fpm


### SET Shopware ENV #######################################
    ARG SHOPWARE_ENV=live
    ENV SHOPWARE_ENV $SHOPWARE_ENV


### Extensions #############################################
    RUN apt-get update
    RUN apt-get install -y wget curl libjpeg62-turbo-dev libpng12-dev libcurl3 libcurl3-dev libxml2-dev php-soap php-apc
    RUN apt-get clean -y


### PHP-Extensions #########################################
    RUN docker-php-source extract &&  \
        docker-php-ext-install pdo pdo_mysql && \
        docker-php-ext-install session && \
        docker-php-ext-install gd && \
        docker-php-ext-install curl && \
        docker-php-ext-install zip && \
        docker-php-ext-install json && \
        docker-php-ext-install hash && \
        docker-php-ext-install opcache && \
        docker-php-ext-install soap && \
        docker-php-source delete


### IONCUBE #################################################
    RUN cd /tmp && \
        wget http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz && \
        tar xfz ioncube_loaders_lin_x86-64.tar.gz && \
        mv ioncube /usr/local/ && \
        echo "zend_extension = /usr/local/ioncube/ioncube_loader_lin_5.6.so" >> "/usr/local/etc/php/conf.d/00-ioncube.ini"


### Install APCu ############################################
    ADD https://pecl.php.net/get/apcu-5.1.3.tgz /tmp/apcu.tar.gz
    RUN mkdir -p /usr/src/php/ext/apcu && tar xf /tmp/apcu.tar.gz -C /usr/src/php/ext/apcu --strip-components=1
    RUN docker-php-ext-configure apcu && docker-php-ext-install apcu
    RUN rm -rd /usr/src/php/ext/apcu && rm /tmp/apcu.tar.gz

    ADD https://pecl.php.net/get/apcu_bc-1.0.3.tgz /tmp/apcu_bc.tar.gz
    RUN mkdir -p /usr/src/php/ext/apcu-bc && tar xf /tmp/apcu_bc.tar.gz -C /usr/src/php/ext/apcu-bc --strip-components=1
    RUN docker-php-ext-configure apcu-bc && docker-php-ext-install apcu-bc
    RUN rm -rd /usr/src/php/ext/apcu-bc && rm /tmp/apcu_bc.tar.gz

    RUN rm /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini
    RUN echo extension=apcu.so > /usr/local/etc/php/conf.d/20-php-ext-apcu.ini

    RUN rm /usr/local/etc/php/conf.d/docker-php-ext-apc.ini
    RUN echo extension=apc.so > /usr/local/etc/php/conf.d/21-php-ext-apc.ini



### User-specific Configs ##################################
    COPY etc/zz-php.ini /usr/local/etc/php/conf.d/
    COPY etc/zz-docker.conf /usr/local/etc/php-fpm.d/