### PHP-Version ############################################
    FROM php:5.6.30-fpm


### SET Shopware ENV #######################################
    ARG SHOPWARE_ENV=live
    ENV SHOPWARE_ENV $SHOPWARE_ENV


### Extensions #############################################
    RUN apt-get update
    RUN apt-get install -y wget curl libjpeg62-turbo-dev libpng12-dev libcurl3 libcurl3-dev libxml2-dev php-soap php-apc
    RUN apt-get clean -y


### PHP-Extensions #########################################
    RUN docker-php-source extract &&  \
        docker-php-ext-install pdo pdo_mysql && \
        docker-php-ext-install session && \
        docker-php-ext-install gd && \
        docker-php-ext-install curl && \
        docker-php-ext-install zip && \
        docker-php-ext-install json && \
        docker-php-ext-install hash && \
        docker-php-ext-install opcache && \
        docker-php-ext-install soap && \
        docker-php-ext-install calendar && \
        docker-php-source delete


### IONCUBE #################################################
    RUN cd /tmp && \
        wget http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz && \
        tar xfz ioncube_loaders_lin_x86-64.tar.gz && \
        mv ioncube /usr/local/ && \
        echo "zend_extension = /usr/local/ioncube/ioncube_loader_lin_5.6.so" >> "/usr/local/etc/php/conf.d/00-ioncube.ini"


### Install APCu ############################################
    RUN apt-get install -y php5-apcu
    RUN mv /usr/lib/php5/20131226/apcu.so /usr/local/lib/php/extensions/no-debug-non-zts-20131226/apcu.so
    RUN echo "extension=apcu.so" >> "/usr/local/etc/php/conf.d/10-apcu.ini"
    RUN echo "apc.enabled=1" >> "/usr/local/etc/php/conf.d/10-apcu.ini"
    RUN echo "apc.enable_cli=1" >> "/usr/local/etc/php/conf.d/10-apcu.ini"


### User-specific Configs ##################################
    COPY etc/zz-php.ini /usr/local/etc/php/conf.d/
    COPY etc/zz-docker.conf /usr/local/etc/php-fpm.d/


### @TODO: Install ImageMagick / imagick  ####################################