### PHP-Version ############################################
    FROM php:7.0-fpm


### SET Shopware ENV #######################################
    ARG SHOPWARE_ENV=live
    ENV SHOPWARE_ENV $SHOPWARE_ENV


### Extensions #############################################
    RUN apt-get update && apt-get install -y wget curl libjpeg62-turbo-dev libpng12-dev libcurl3 libcurl3-dev libxml2-dev
    RUN apt-get clean -y


### PHP-Extensions #########################################
    RUN docker-php-source extract &&  \
        docker-php-ext-install pdo pdo_mysql && \
        docker-php-ext-install session && \
        docker-php-ext-install gd && \
        docker-php-ext-install curl && \
        docker-php-ext-install zip && \
        docker-php-ext-install json && \
        docker-php-ext-install hash && \
        docker-php-ext-install opcache && \
        docker-php-ext-install soap && \
        docker-php-ext-install calendar && \
        docker-php-source delete


### IONCUBE #################################################
    RUN cd /tmp && \
        wget http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz && \
        tar xfz ioncube_loaders_lin_x86-64.tar.gz && \
        mv ioncube /usr/local/ && \
        echo "zend_extension = /usr/local/ioncube/ioncube_loader_lin_7.0.so" >> "/usr/local/etc/php/conf.d/00-ioncube.ini"


### Install APCu ############################################
    RUN wget -O /tmp/apcu.tar.gz https://pecl.php.net/get/apcu-5.1.3.tgz
    RUN mkdir /tmp/apcu/ && tar -zxvf /tmp/apcu.tar.gz -C /tmp/apcu/
    RUN mkdir -p /usr/src/php/ext/apcu && mv /tmp/apcu/apcu-5.1.3/* /usr/src/php/ext/apcu
    RUN docker-php-ext-configure apcu && docker-php-ext-install apcu
    RUN rm -rd /usr/src/php/ext/apcu && rm -rf /tmp/apcu.tar.gz

    RUN wget -O /tmp/apcu_bc.tar.gz https://pecl.php.net/get/apcu_bc-1.0.3.tgz
    RUN mkdir /tmp/apcu_bc/ && tar -zxvf /tmp/apcu_bc.tar.gz -C /tmp/apcu_bc/
    RUN mkdir -p /usr/src/php/ext/apcu-bc && mv /tmp/apcu_bc/apcu_bc-1.0.3/* /usr/src/php/ext/apcu-bc
    RUN docker-php-ext-configure apcu-bc && docker-php-ext-install apcu-bc
    RUN rm -rd /usr/src/php/ext/apcu-bc && rm -rf /tmp/apcu_bc.tar.gz

    RUN rm /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini
    RUN echo extension=apcu.so > /usr/local/etc/php/conf.d/20-php-ext-apcu.ini

    RUN rm /usr/local/etc/php/conf.d/docker-php-ext-apc.ini
    RUN echo extension=apc.so > /usr/local/etc/php/conf.d/21-php-ext-apc.ini



### User-specific Configs ##################################
    COPY etc/zz-php.ini /usr/local/etc/php/conf.d/
    COPY etc/zz-docker.conf /usr/local/etc/php-fpm.d/


### ImageMagick install ####################################
    RUN apt-get -y update
    RUN apt-get -y install libmagickwand-dev --no-install-recommends
    RUN pecl install imagick
    RUN docker-php-ext-enable imagick


### GD install ##############################################
    RUN apt-get -y install  libfreetype6-dev libjpeg62-turbo-dev libpng12-dev libxpm-dev libvpx-dev
    RUN docker-php-ext-configure gd \
            --with-freetype-dir=/usr/lib/x86_64-linux-gnu/ \
            --with-jpeg-dir=/usr/lib/x86_64-linux-gnu/ \
            --with-xpm-dir=/usr/lib/x86_64-linux-gnu/ \
            --with-vpx-dir=/usr/lib/x86_64-linux-gnu/
    RUN docker-php-ext-install gd
    RUN rm -r /var/lib/apt/lists/*


### GD install ##############################################
    RUN apt-get -y update \
        && apt-get install -y libicu-dev\
        && docker-php-ext-configure intl \
        && docker-php-ext-install intl


### MEMCACHED ################################################
    RUN apt-get update \
        && buildDeps="git libmemcached-dev zlib1g-dev" \
        && doNotUninstall="libmemcached11 libmemcachedutil2" \
        && apt-get install -y $buildDeps --no-install-recommends \
        && rm -r /var/lib/apt/lists/* \
        && docker-php-source extract \
        && git clone --branch php7 https://github.com/php-memcached-dev/php-memcached /usr/src/php/ext/memcached/ \
        && docker-php-ext-install memcached \
        && docker-php-source delete \
        && apt-mark manual $doNotUninstall \
        && apt-get purge -y $buildDeps


### TIMEZONE  #################################################
    ENV TZ=Europe/Berlin


### REDIS  ####################################################
    RUN pecl install redis-3.1.6 \
        && docker-php-ext-enable redis