### MySQL-Version ############################################
    FROM mysql:5.7.17


    ENV TZ=Europe/Berlin
    RUN ln -snf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo Europe/Berlin > /etc/timezone